"""
Database models for AI-Scheduler
"""
from datetime import datetime
from typing import Optional
from sqlalchemy import Column, Integer, String, DateTime, Text, ForeignKey, Enum, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
import enum

Base = declarative_base()


class TaskStatus(enum.Enum):
    """Task status enumeration"""
    DUE = 0
    COMPLETED = 1
    MISSED = -1


class TaskCategory(enum.Enum):
    """Task category enumeration"""
    DAILY = "daily"
    WEEKLY = "weekly"
    MILESTONE = "milestone"
    GOAL = "goal"


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    phone = Column(String(20), unique=True, nullable=False, index=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    goals = relationship("Goal", back_populates="user", cascade="all, delete-orphan")
    tasks = relationship("Task", back_populates="user", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<User(id={self.id}, phone='{self.phone}')>"


class Goal(Base):
    """
    Long-term goals table
    Represents the highest level of planning
    """
    __tablename__ = "goals"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    target_date = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    status = Column(String(50), default="active")  # active, completed, archived
    
    # Relationships
    user = relationship("User", back_populates="goals")
    milestones = relationship("Milestone", back_populates="goal", cascade="all, delete-orphan")
    roadmap = relationship("Roadmap", back_populates="goal", uselist=False, cascade="all, delete-orphan")
    recalibration_logs = relationship("RecalibrationLog", back_populates="goal", cascade="all, delete-orphan")
    conversation_history = relationship("ConversationHistory", back_populates="goal", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Goal(id={self.id}, title='{self.title}')>"


class Roadmap(Base):
    """
    Roadmap generated by AI for a specific goal
    Stores the overall plan/strategy
    """
    __tablename__ = "roadmaps"

    id = Column(Integer, primary_key=True, index=True)
    goal_id = Column(Integer, ForeignKey("goals.id"), nullable=False, unique=True)
    roadmap_text = Column(Text, nullable=False)  # AI-generated roadmap
    phases = Column(Text, nullable=True)  # JSON string of phases
    approved = Column(Integer, default=0)  # 0 = draft, 1 = approved
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    goal = relationship("Goal", back_populates="roadmap")

    def __repr__(self):
        return f"<Roadmap(id={self.id}, goal_id={self.goal_id}, approved={self.approved})>"


class Milestone(Base):
    """
    Milestones/Phases extracted from the roadmap
    """
    __tablename__ = "milestones"

    id = Column(Integer, primary_key=True, index=True)
    goal_id = Column(Integer, ForeignKey("goals.id"), nullable=False)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    order_index = Column(Integer, default=0)  # For ordering milestones
    target_date = Column(DateTime, nullable=True)
    completed_date = Column(DateTime, nullable=True)
    status = Column(String(50), default="pending")  # pending, in_progress, completed
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    goal = relationship("Goal", back_populates="milestones")
    tasks = relationship("Task", back_populates="milestone", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Milestone(id={self.id}, title='{self.title}', status='{self.status}')>"


class Task(Base):
    """
    Individual tasks/to-dos
    Can be daily, weekly, or linked to milestones
    """
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    milestone_id = Column(Integer, ForeignKey("milestones.id"), nullable=True)
    title = Column(Text, nullable=False)
    description = Column(Text, nullable=True)
    category = Column(String(50), default="daily")  # daily, weekly, milestone
    status = Column(Integer, default=0)  # 0=due, 1=completed, -1=missed
    priority = Column(Integer, default=0)  # Higher number = higher priority
    scheduled_date = Column(DateTime, nullable=True)  # When task should be done
    completed_date = Column(DateTime, nullable=True)  # When task was actually completed
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    user = relationship("User", back_populates="tasks")
    milestone = relationship("Milestone", back_populates="tasks")
    audit_logs = relationship("AuditLog", back_populates="task", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Task(id={self.id}, title='{self.title}', status={self.status})>"


class AuditLog(Base):
    """
    Audit log for tracking changes to tasks
    Allows users to see what was changed and when
    """
    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    task_id = Column(Integer, ForeignKey("tasks.id"), nullable=True)
    action = Column(String(50), nullable=False)  # created, updated, deleted, status_changed
    field_name = Column(String(100), nullable=True)  # Which field was changed
    old_value = Column(Text, nullable=True)
    new_value = Column(Text, nullable=True)
    reason = Column(Text, nullable=True)  # Why the change was made
    timestamp = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    task = relationship("Task", back_populates="audit_logs")

    def __repr__(self):
        return f"<AuditLog(id={self.id}, task_id={self.task_id}, action='{self.action}')>"


class RecalibrationLog(Base):
    """
    Logs of automatic recalibrations performed by the system
    Tracks when the system adjusted the schedule
    """
    __tablename__ = "recalibration_logs"

    id = Column(Integer, primary_key=True, index=True)
    goal_id = Column(Integer, ForeignKey("goals.id"), nullable=True)
    reason = Column(Text, nullable=False)  # Why recalibration was triggered
    changes_made = Column(Text, nullable=True)  # JSON string of changes
    tasks_affected = Column(Text, nullable=True)  # JSON array of task IDs
    timestamp = Column(DateTime, default=datetime.utcnow)

    # Relationships
    goal = relationship("Goal", back_populates="recalibration_logs")

    def __repr__(self):
        return f"<RecalibrationLog(id={self.id}, goal_id={self.goal_id})>"


class ConversationHistory(Base):
    """
    Store conversation history with AI for context
    """
    __tablename__ = "conversation_history"

    id = Column(Integer, primary_key=True, index=True)
    goal_id = Column(Integer, ForeignKey("goals.id"), nullable=True)
    role = Column(String(20), nullable=False)  # user or assistant
    content = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow)

    # Relationships
    goal = relationship("Goal", back_populates="conversation_history")

    def __repr__(self):
        return f"<ConversationHistory(id={self.id}, role='{self.role}')>"